name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy@v1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          flatten: true
